version: '3.7'

services:
  teamcity-server:
    container_name: teamcity-server
    image: jetbrains/teamcity-server
    volumes:
      - './data:/data/teamcity_server/datadir'
      - './logs:/opt/teamcity/logs'
    ports:
      - 8111:8111

volumes:
  data:
  logs:
    driver: local