version: '3'

services:
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "53603:53603"
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: root