version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    privileged: true
    user: root
    ports:
      - "80:8080"
      - "50000:50000"
    volumes:
      - ./data:/var/jenkins_home