version: '3.7'

services:
  mysql:
    container_name: mysql
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: frank
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql

volumes:
  data:
    driver: local