version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: frank
    volumes:
      - ./local-data:/var/lib/postgresql/data
    ports:
      - 5432:5432