version: '3.7'

services:
  redis:
    container_name: redis
    image: docker.io/bitnami/redis:6.2-debian-10
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - 6379:6379
    volumes:
      - './data:/bitnami/redis/data'

volumes:
  data:
    driver: local